spring.application.name=histobe

# src/main/resources/application.properties

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional, aber hilfreich:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# NARA API Konfiguration
nara.api.url=https://catalog.archives.gov/api/v2/records/search
nara.api.key=tPl1Q9M0K55b8UcG8XI8p4w2K9TomruPaSQh5kRu